services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    healthcheck:
      test: [ "CMD-SHELL", "psql -U local -d store -p 5450 -c \"SELECT 1\" || exit 1" ]
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - local-postgres-volume:/var/lib/postgresql/data
    command: postgres -c port=5450
    ports:
      - "5450:5450"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store

  minio:
    image: minio/minio
    container_name: local-minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9900/minio/health/live"]
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - local-minio-volume:/data
    command: server /data --address ":9900" --console-address ":9901"
    ports:
      - "9900:9900"
      - "9901:9901"
    environment:
      MINIO_ROOT_USER: local
      MINIO_ROOT_PASSWORD: password

  mailhog:
    image: mailhog/mailhog
    container_name: local-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  local-postgres-volume:
  local-minio-volume: