services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    healthcheck:
      test: [ "CMD-SHELL", "psql -U local -d store -p 5450 -c \"SELECT 1\" || exit 1" ]
      start_period: 3s
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - local-postgres-volume:/var/lib/postgresql/data
    command: postgres -c port=5450
    ports:
      - "5450:5450"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store

volumes:
  local-postgres-volume: