"""update pk in order_items table

Revision ID: 2f0bb391b695
Revises: c6ac40d20b12
Create Date: 2025-08-02 05:46:56.635097

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2f0bb391b695'
down_revision: Union[str, Sequence[str], None] = 'c6ac40d20b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_cart_id_product_id_key'), 'cart_items', type_='unique')
    op.drop_column('cart_items', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('cart_items_cart_id_product_id_key'), 'cart_items', ['cart_id', 'product_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
